### ISSUE TITLE
Validation of Array with duplication is wrong

### ISSUE THREAD

**Issue by reubinoff** [h4t0n/mongoose-idexists#1]
lets assume we have mode:

const Test = new Schema({
    name: { type: String, required: true, unique: true },
    scenarios: [{
        type: Schema.Types.ObjectId,
        ref: 'Scenario'
    }]
})

and to create this entity we create from Mode:
test= {
name: "MosheReubinoff",
scenarios:[
"some_hash_type_A",
"some_hash_type_A"
]}

this will failed in validation because you check the count of scenarios which return 1 although we actually have 2.

in my opinion we need first to remove duplications from original array and to check the count against this list.

**Comment by h4t0n** [comment]
I don't understand your issue. The check is performed in the ref table Scenario. Please, write a full test case that fails.
